### ISSUE TITLE
Options are Ignored

### ISSUE THREAD

**Issue by f2prateek** [segment-integrations/analytics.js-integration-amplitude#14]
The options declared here - https://github.com/segment-integrations/analytics.js-integration-amplitude/blob/master/lib/index.js#L35-L37 are never actually set on the Amplitude library.

We should set them when we initialize the library here https://github.com/segment-integrations/analytics.js-integration-amplitude/blob/master/lib/index.js#L54-L57.

**Comment by hankim813** [comment]
@f2prateek added this to jira https://segment.atlassian.net/browse/INT-175
