### ISSUE TITLE
Multiple page events fired if using trackAllPages

### ISSUE THREAD

**Issue by elgreg** [segment-integrations/analytics.js-integration-amplitude#37]
If I enable trackAllPages and then fire .page with a named page it ends up sending two events to amplitude. This is because the page event does not return after firing the first. Is this behavior expected?

For example:

If my configuration has:

```
        "Amplitude": {
          apiKey: "[blah]",
          trackAllPages: true,
          saveEvents: true,
          includeUtm: true,
          includeReferrer: true,
          includeGclid: true,
          saveParamsReferrerOncePerSession: false,
          domain: "." + document.location.host
        },
```
  
And I call analytics.page('test')

The code first hits https://github.com/segment-integrations/analytics.js-integration-amplitude/blame/master/lib/index.js#L125

```
  // all pages
  if (opts.trackAllPages) {
    this.track(page.track());
  }
```

This sends an event to amplitude with event_type: "Loaded a Page" (per what's in [analytics.js](https://github.com/segmentio/analytics.js/blob/master/analytics.js#L3088))

and then gets to https://github.com/segment-integrations/analytics.js-integration-amplitude/blob/master/lib/index.js#L134

```
  // named pages
  if (name && opts.trackNamedPages) {
    this.track(page.track(name));
  }
```

Which then sends another event to amplitude with the event_type: "Viewed test Page"

Would it make more sense to have the trackAllPages add the name or category if present and return? e.g.

```
  // all pages
  if (opts.trackAllPages) {
    if(category){
      return this.track(page.track(category));
    }
    if(name){
      return this.track(page.track(name));
    }
    return this.track(page.track());
  }
```

Kind of gross, I know.

**Comment by ucarion** [comment]
Hey @elgreg,

Terribly sorry for the massive delay in responding to this ticket; it fell through the cracks.

The settings "Track All Pages", "Track Named Pages", and "Track Categorized Pages" are commonly used in a bunch of our integrations, so changing their behavior isn't really an option -- it would be really surprising if Amplitude worked differently from all other integrations. It would also break things for existing users of the integration.

As you have pointed out, if you have all three settings enabled, then it's possible for three Amplitude events to get sent for one Segment event. If you really want only one event to get sent, only enable one of those settings. Personally, I use "Track All Pages", and then in Amplitude or other end tools I filter by the event properties "name"/"category".

Thanks for the thoughtful suggestion, though. I think the behavior you describe is a solid option. But the deciding factor here is consistency across integrations, and maintaining backwards compatibility.
